### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/react-crash#1]
This repository is in need of some relevant issue templates.

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by FahimFBA** [comment]
> Can I get assigned? let me know how to start.

Sure! You can follow this repository: https://github.com/FahimFBA/RainyRoof_Restaurant_Website

First of all, make sure to fork this repository and create a new branch where you will make the changes.

**Comment by FahimFBA** [comment]
Closing this issue as PR #3 solved it.
