### ISSUE TITLE
Link addition to the content box

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/react-crash#2]
Add the links (IMDb for movies/tv series) to the checkbox.

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by Akash1965** [comment]
@FahimFBA can i get assigned to this issue? Would love to work on it

**Comment by FahimFBA** [comment]
> Can I get assigned? let me know how to start.

As you have already worked on an issue, I think I can give another person a chance to work on an open source project, @Pulkitxm. 😃

**Comment by FahimFBA** [comment]
> @FahimFBA can i get assigned to this issue? Would love to work on it

Sure! Go ahead! I'm assigning you for this, @Akash1965. 👍 

Please also make sure to include `closes #2` in the Pull Request.

**Comment by Akash1965** [comment]
@FahimFBA The ondb api that is being used doesn't return a url for the movie/tv links

**Comment by FahimFBA** [comment]
> @FahimFBA The ondb api that is being used doesn't return a url for the movie/tv links

Can you make some changes like another free API to call for the IMDb link based on the relevant movie name?

**Comment by Akash1965** [comment]
I searched a lot but unfortunately i was unable to find any api that will be appropriate to solve this issue

**Comment by FahimFBA** [comment]
> I searched a lot but unfortunately i was unable to find any api that will be appropriate to solve this issue

I see! Then we can close this issue. Thanks for all your help. 😃
